### ISSUE TITLE
Need only ldap and SMB honeypot plus logging

### ISSUE THREAD

**Issue by Blason** [qeeqbox/seahorse#1]
Hi ,

I was going through the project and I need only ldap and SMB honeypots from configuration. Plus would you please confirm about location of logging of data or hits to monitor the traffic?

**Comment by giga-a** [comment]
Hey @Blason, sorry for the delay

I am working on having all the services separated instead of having them all in one box. This will allow users to pick which honeypots they want

This project should log smb and ldap as the following:

`
/var/log/ldap.logs
/var/log/samba/log.smbd
`

Are you having issues with those log files?
